language: python
python:
  - "3.8"
install:
  - python ./cli.py decrypt
  - base64 --decode $TOKEN > google_drive_token.pickle
  - python ./cli.py data
  - ls data
script:
  - python ./cli.py lint
  - python ./cli.py test
