language: python
dist: xenial
sudo: required
python:
- 3.6
- 3.7
services:
- docker
before_install:
- docker pull rabbitmq:3.8.0-beta.5
- docker container run -d -p 5672:5672 -p 15672:15672 --name "rabbitmq" rabbitmq:3.8.0-beta.5
install:
- pip install pipenv
- pipenv install
- python setup.py bdist_wheel
script:
- python -m unittest discover
- docker build -t ucsde4e/baboon_tracking .
deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker image push ucsde4e/baboon_tracking
  on:
    branch: master
