language: python
dist: xenial
sudo: required
python:
- 3.6
- 3.7
services:
- docker
before_install:
- docker pull rabbitmq:3.8.0-beta.5
- docker container run -d -p 5672:5672 -p 15672:15672 --name "rabbitmq" rabbitmq:3.8.0-beta.5
install:
- pip install pipenv
- pipenv install
- python setup.py bdist_wheel
script:
- python -m unittest discover
- docker build -t ucsde4e/baboon_tracking .
deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker image push ucsde4e/baboon_tracking
  on:
    branch: master

# STORES CREDENTIALS TO DOCKERHUB, DO NOT REMOVE
env:
  matrix:
  - secure: FtqZtRw6bswtM4tA1LjA8mze41nLOt2l8pouxSXRusYwraEsPqTF2bHrgujABb/V6RyGSV2M+DzmqYAy7RufPNDhg8Rc9wmVvyUIUurr+xsUhyuMgfEOllSYPqGOqNBIzEqm1X84ZrXBOhNm2stgH4q0XPqKgiogo6FsWvFYWp3wCk/A++GLC2T35+xiItPwT7qjM8k3qJ/ybtdmyc9ZwtvR65j1bJ5N2s2YzPjSbyvQ/FxX39ICIpezAq4QKHxy3bZiiCBP275/bm8FcA5azbOrFEtrMwo3yMrs3UONOhli03VEKT5OpVwE67dsajpqhtj6U/8DIpaGCJRy+bik/++YbTJJt8hf+jlp5QKROSvhJglkhMLyzFH/T8uGoBh4KCDwOIhpvuJ+JtSKZhtS9AvZE/+YjXvmdgCWIrf986fajIoxmoAx0b/haSf1+MDvb8UkVgfMMBpyKah/D/6O111JS5/9sbPHjsBOaL95VZqd/PUyHqXVkFe36jHY35VrlVH+gbBzbAS0OkyivTfSzZmOn3JecFQ6NLbCxXUoU5XGjNMlzY/x130ko9Ax1ZhU5iKscCW29mG3Jv7Pr76ZYDu1bUvyuLYqFwA3VQ8uonE+ADgiCeBPKEw9vGDmgfJJwu2DkS3+bRLoQJTat55fZemvnZuU00T1J3fDHAdbQ0M=
  - secure: eSYhwOt7QUujdO3EKoJ4LMl9Ec2t4htv3W5nbGpji/K460dpoGYOMY8NodXC3qGiHTwZ5grWmNRqrpe90aEHax8ssw1NsdttZEeSVYOVgGFGf2J0Q1OpSvMkLQWvuj9/HmOKL7Kx8JimsS59EK9SbdG3oZ6mGnyKZisyYVCpkIlwUAHIjq0e4HZEtk7UTtVhNi8uEbaRwEybbZMhSzcIzqikPiXKTFDLRUTF8Oj0P/lo3v8NO2+eYo1Ig4Z3so9UaD5UgCp5DI+QzaTsiKbusw/6kWY2TSy110l255bJXdPuL3ymWNNIf26sOSOiUzAe/+pqGDLZ3gAlOZyKmtRcr0Q3lHzpQp8zUCRvzuUpUldsA7NGoZAJuxrzzXbLOkI8SoUco23ABEsJIXl0s0Wl24PmyrrYBrVDFeMJJZ+/dlj1Qo/+muCUnCaUxaE3fn6rZI2XJPF7iyxcV4X+GGUNg5LdlPNqcUrL7lMu6Ovy3KO3axnPkgMM4JRQUTRo6GxAvT8MJwjkB3xrPadP8F9PYR8HhBZFOup6DNFY4mSCtVpI0fkzhI5mLgZDBv6alz8G7twrxjZhyxDPmH7YtmV2cD9xN5CA/Tz1QyydSGmN8Y+HkrPPgTiP8pjz2KoDk+5KKDsTebp2djQ4xzueFKKusunxZ4U4nzkqY+onSXEByo0=
