language: python
python:
  - "3.8"
install:
  - echo noop
script:
  - python ./cli.py lint
  - python ./cli.py test
  - python ./cli.py docs
after_success:
  - travis-sphinx deploy -b master,feature/integration-tests
