input:
  type: string
  skip_learn: true
output:
  type: string
  skip_learn: true
mask_output:
  type: string
  skip_learn: true

preprocess:
  kernel_size:
    type: int32
    min: 1
    odd: true
    std: 1

motion_detector:
  history_frames:
    type: int32
    min: 1
    std: 0.5

  registration:
    max_features:
      type: int32
      min: 0
      std: 5
    good_match_percent:
      type: float
      min: 0
      max: 1
      std: 0.1

  quantize_frames:
    scale_factor:
      type: int32
      min: 0
      std: 2

  noise_reduction:
    erode_kernel_size:
      type: int32
      min: 0
      std: 0.5
    dilate_kernel_size:
      type: int32
      min: 0
      std: 1
    combine_kernel_size:
      type: int32
      min: 0
      std: 0.5

  hysteresis:
      required_motion_observations:
        type: int32
        min: 0
        std: 0.1
      required_no_motion_observations: 1
        type: int32
        min: 0
        std: 0.1
