input: './data/input.mp4'
output: './output/output.mp4'
mask_output: './output/mask.mp4'

preprocess:
    kernel_size: 5

motion_detector:
    history_frames: 8

    registration:
        good_match_percent: 0.15
        ransac_max_error: 5.0
        ssc_num_ret_points: 10000
        ssc_tolerence: 0.1

    quantize_frames:
        scale_factor: 40

    noise_reduction:
        erode_kernel_size: 6
        dilate_kernel_size: 30
        combine_kernel_size: 12

    hysteresis:
        required_motion_observations: 1
        required_no_motion_observations: 1

    group_filter:
        size: 7
