version: "3.7"
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8.0-beta.5
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - imshow_net
    jupyter:
        container_name: juypter
        image: anhdngo/baboon_tracking
        build:
            dockerfile: Dockerfile
            context: ./
        ports:   
            - "8888:8888"
        networks:
            - imshow_net
        environment:
            - RABBIT_IP='rabbit'
            - RABBIT_PORT='5672'

networks:
    imshow_net:

volumes:
    data:
    output:
