[tool.poetry]
name = "baboon-tracking"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.0"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
google-api-python-client = "^1.9.3"
google-auth-httplib2 = "^0.0.3"
google-auth-oauthlib = "^0.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
