name: C++ Docker Environment Build

on:
  push:
    branches: [ master, feature/cpp ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cxx

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build CPU Container
      uses: docker/build-push-action@v2
      with:
        context: ./cxx
        push: true
        file: ./cxx/Dockerfile.CPU
        tags: ghcr.io/ucsd-e4e/baboon-tracking:cpu
    - name: Build CUDA 6.1 Container
      uses: docker/build-push-action@v2
      with:
        context: ./cxx
        push: true
        file: ./cxx/Dockerfile.CUDA
        tags: ghcr.io/ucsd-e4e/baboon-tracking:cuda-6.1
        build-args: |
          CUDA_ARCH_BIN=6.1
    - name: Build CUDA 7.5 Container
      uses: docker/build-push-action@v2
      with:
        context: ./cxx
        push: true
        file: ./cxx/Dockerfile.CUDA
        tags: ghcr.io/ucsd-e4e/baboon-tracking:cuda-7.5
        build-args: |
          CUDA_ARCH_BIN=7.5
